### ISSUE TITLE
Preparation of F-Droid package

### ISSUE THREAD

**Issue by stephanritscher** [stephanritscher/Simple-Contacts#1]
@Glaser-Martin It seems our discussion in #156 was not welcome. We can continue in this issue (now that I found out how to enable issues for a fork).
As a short 
- You suggested to create an [F-Droid package](https://gitlab.com/fdroid/rfp/-/issues/2241) for this fork and I agreed.
- We discussed that master branch will be the package to be published while a separate branch `structured-address` will only contain the new feature in case a later upstream integration would be considered.
- This results in a merge chain `SimpleMobileTools/Simple-Contacts:master` -> `stephanritscher/Simple-Contacts:structured-address` -> `stephanritscher/Simple-Contacts:structured-address`.
- You assembled places to change which I adapted here: dc4c4aeedca4919a2913ae59944d9e6c464c1e93
- F-Droid seems to use tags for releases and SimpleMobileTools uses 3-digit releases (e.g. 6.19.1), so you suggested to add a fourth digit to keep the base release as reference and have flexibility of multiple releases per base release. I created 6.19.1.1 as first own tag.

**Comment by stephanritscher** [comment]
I just deleted the upstream tags > 6.19.1 on my fork. They came in when I synced my repo as tags are not associated to branches. This probably means that the branch setup is not relevant for F-Droid.

**Comment by Glaser-Martin** [comment]
Hello @stephanritscher, 

interesting and strange, I never thought that this could happen. But it won't stop us anyhow, will it?

Tags now look really good. 

Thank you very much.

I prepared the metadata file [de.ritscher.simplemobiletools.contacts.pro.yml.zip](https://github.com/stephanritscher/Simple-Contacts/files/10014281/de.ritscher.simplemobiletools.contacts.pro.yml.zip) - zip as GitHub does not allow to add a yml file - for F-Droid.

I thought that I keep the references to the original where ever it makes sense, but with the latest development I have doubts if that is the right thing to do. I asked tibbi a question in SimpleMobileTools#156 and want to wait for the answer before I go forward with the F-Droid-Request. I hope there will be an answer. Independently you can think about your opinion already...

My thoughts:

- AuthorName could as well be your name,
-  AuthorEmail is a problem, but it might be possible to not provide it,
-  WebSite could be simply the GitHub address like in SourceCode, 
- IssueTracker I would rather not change, because most issues will concern the original, so users should post issues there, 
- Donate/Bitcoin/Litecoin could be taken out.

Best Regards 

 Martin

**Comment by Glaser-Martin** [comment]
Hello @stephanritscher,

thank you so much!

Best Regards

 Martin

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

never mind. Thanks for the initiative!

Best regards,
Stephan

PS: Small warning: I'll refactor the commit history to make changes compared to upstream easier to grasp. This will remove your commits (from the master branch) and replace them by similar / combined commits authored by me. I'll add you to the contributors list visible in the about activity though.
If you want to contribute again, use a fresh clone of the repository or use `git fetch` followed by `git reset --hard master` (this will remove all local changes).

**Comment by Glaser-Martin** [comment]
Hi @stephanritscher,

no worries, just do whatever you like, no need to spend effort to keep my name anywhere.

I did not use git for the modifications but the GitHub UI. That is why the commits I did are in that shape.

I think that I made a mistake with the icons: 
I copied in app/src/main/res/mipmap-anydpi-v26 the file ic_launcher_green.xml to ic_launcher.xml and in app/src/main/res/mipmap-*hdpi (4 folders) the file ic_launcher_green.png to ic_launcher.png in order to change the standard icon to be green. But now it is so that when selecting in the configuration dialog the orange color, the green icon is shown. So these changes should better be reverted. 

There must be somewhere a definition which color and icon is used by default. The list of available colors and icons seems to be defined in app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/SimpleActivity.kt in getAppIconIds. But I can't find where is defined the default color/icon to use.

Somehow the pictures I changed in fastlane/metadata/android/en-US/images/*Screenshots got lost. At least fastlane/metadata/android/en-US/images/contacts.xcf on which all these pictures are based and in which I changed orange to green color is still there.

Best Regards

 Martin

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin ,

when I did the rebase I also fixed the issue with the icons you described. Please try version 6.22.2.2 (apk is available [here](https://github.com/stephanritscher/Simple-Contacts/releases/tag/6.22.2.2), F-droid usually needs half a week for publishing new releases.

I'll have a look at the sceenshots I missed. The old commits are still there so I should be able to recover them.

Best regards,
Stephan

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

I double checked but I find any screenshots you uploaded.
[Here](https://github.com/stephanritscher/Simple-Contacts/tree/95f85fe2b1977278ca1ff30ff73a376a2a0387b2) you can see the status of the repository before the refactoring.
[Here](https://github.com/stephanritscher/Simple-Contacts/commits/95f85fe2b1977278ca1ff30ff73a376a2a0387b2) you can see the list of all commits up to that time (navigate them using "Older" / "Newer" buttons).
[This](https://github.com/stephanritscher/Simple-Contacts/commits/95f85fe2b1977278ca1ff30ff73a376a2a0387b2?author=Glaser-Martin) should be the complete list of commits by you.

Honestly, I didn't pay too much attention to the screenshots before. Might it be you only changed/uploaded featureGraphic but not the screenshots in the *Screenshots folders? At least from what I can see they must have gotten lost earlier.

Anyways, it doesn't sound like you still have a local copy of the changed files, do you? Would you mind recreating the changed screenshots?

Best regards,
Stephan

**Comment by Glaser-Martin** [comment]
Hi @stephanritscher,

you are right, I never changed the screenshots, I changed and uploaded only featureGraphic. I forgot about that completely. Sorry.

Here are the 4 screenshots:

![1](https://user-images.githubusercontent.com/116721092/233451830-7785f109-e5cb-469b-b5dd-56e7e5a60479.jpeg)

![2](https://user-images.githubusercontent.com/116721092/233451826-0cd64afe-9d87-4bae-9f75-4641e90656b1.jpeg)

![3](https://user-images.githubusercontent.com/116721092/233451823-7b45197d-ae69-4b05-9eab-50a2ed91c84f.jpeg)

![4](https://user-images.githubusercontent.com/116721092/233451814-be569fe4-6f32-4c1d-a833-c98469f32780.jpeg)

Best Regards

 Martin

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

thanks. I added them to the repo and removed the others. I hope they will get picked up by F-Droid correctly with the next release.

Best regards,
Stephan
