### ISSUE TITLE
Third party contacts not present after update

### ISSUE THREAD

**Issue by Mrothyr** [stephanritscher/Simple-Contacts#20]
Hi,

I use your version since I migrate to GrapheneOS. The last version I use before was 6.22.4.2, installed directly from Github via Obtainium. I update yesterday to 6.22.7.2 and lost access to all contacts in my work account, synchronised by Nine or Outlook. The accounts are not longer presented in the filter. I rolled back to 6.22.4.2.

CU

**Comment by stephanritscher** [comment]
Hi,

sorry for the late reply.
I'm using 6.22.7.2 myself without such problem, but not on GrapheneOS.
Since upstream stopped releasing source, I intend to contribute my changes to the fork FossyfyOrg/Contacts. Watch out for PR https://github.com/FossifyOrg/Contacts/pull/57.
Bugfixing would best be there, except you have a good hint on the source of the problem (e.g. a stacktrace in an adb log or similar).

Best regards,
Stephan
