### ISSUE TITLE
Configuring default primary address book for editing my contacts

### ISSUE THREAD

**Issue by mh182** [stephanritscher/Simple-Contacts#8]
First, a big thanks for providing the app. I was searching for an open source contact app handles the address entries correctly.
And your fork does that well.

But now the "but": I was confused when I tried to change an address the first time.

Even though the address was shown in the contact app, when I selected the edit button, the address data was empty.
When I left the edit mode, the address was shown again.

It took me a while to find the cause of this "apparent bug". The contact app contains the information of 3 accounts: my primary contacts provided by a carddav server using DAVx5, Signal, and Telegram. When I go into edit mode, the "Signal" account is selected, which contains no address data.

Worst of all, the used account is at the bottom of the screen, well hidden.

Is there a way to configure the contact app so editing a contact uses my primary address book from DAVx5 instead of using the Signal account?

**Comment by stephanritscher** [comment]
I think there isn't and really you would have to specify a complete ordering of all accounts, not only one primary, to solve this thoroughly. It seems there is some automatic detection which computes a string reprentation of the contact per account and uses the account with the longest representation as primary. This works reasonably fine for me (though not a Signal use, I must admit). If not, you can still click on the account name at the bottom of the contact view instead of the edit button on top.
If that doesn't help you might try to discuss the issue with tibbi, the original author. His changes will also land in this fork eventuall.
